#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : debtcollector
Version  : 1.12.0
Release  : 33
URL      : http://tarballs.openstack.org/debtcollector/debtcollector-1.12.0.tar.gz
Source0  : http://tarballs.openstack.org/debtcollector/debtcollector-1.12.0.tar.gz
Source99 : http://tarballs.openstack.org/debtcollector/debtcollector-1.12.0.tar.gz.asc
Summary  : A collection of Python deprecation patterns and strategies that help you collect your technical debt in a non-destructive manner.
Group    : Development/Tools
License  : Apache-2.0
Requires: debtcollector-python
Requires: funcsigs
Requires: pbr
Requires: six
Requires: wrapt
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/debtcollector.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the debtcollector package.
Group: Default

%description python
python components for the debtcollector package.


%prep
%setup -q -n debtcollector-1.12.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490889717
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1490889717
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
